### ISSUE TITLE
404 on link to White Paper on Open Source Integration using the Base SAS Java Object

### ISSUE THREAD

**Issue by bheinsius** [sassoftware/enlighten-integration#4]
On https://github.com/sassoftware/enlighten-integration, the link to White Paper on Open Source Integration using the Base SAS Java Object (https://github.com/sassoftware/enlighten-integration/blob/master/SAS_Base_OpenSrcIntegration/SAS_Base_OpenSrcIntegration.pdf) gives a 404 page not found.

**Comment by brettwujek** [comment]
Thanks - the missing file has been added.
